### PR TITLE
feat - grid component

### PR DESCRIPTION
**Pull request by prachi-sahani**
Created grids
Variations included
 - basic 2 column grid
 - basic 3 column grid
 - col-lg, col-md, col-sm classes for responsive design(similar to bootstrap but only for 2 and 3 col grids)

grid

### CODE REVIEW

**Review by dev-enforced — APPROVED** [review]
Output generated by this CSS snippet seems Good to me . You can post the HTML file too so that we can get a clearer idea of the structure shown in the photo.Good use of media queries and the comments.

**Review by omgaikwad — COMMENTED** [review]
Code looks good, you can merge

**Review by raghav2110 — COMMENTED** [review]
Looks good to merge

**Comment by prachi-sahani** [comment]
> Output generated by this CSS snippet seems Good to me . You can post the HTML file too so that we can get a clearer idea of the structure shown in the photo.Good use of media queries and the comments.

Sure, will share it along with the documentation site

**Pull request merged**
