### PR TITLE
feat - card component

### PR DESCRIPTION
**Pull request by prachi-sahani**
Created cards component
Types of cards included:
 - basic card(only text)
 - card with footer
 - card with image
 - card with dismiss
 - card with overlay
 - card with badge
 - horizontal card

Screenshot 2022-02-05 175559

127 0 0 1_5500_html_components_card html (1)

### CODE REVIEW

**Review by FarhanMobashir — COMMENTED** [review]
All good

**Review by junaidshaikh-js — COMMENTED** [review]
Looks good to me!

**Review by stutisk — COMMENTED** [review]
Overall code looks good to me

**Review by GuptaEesh — COMMENTED** [review]
Looks good to me

**Pull request merged**
